// AUTO-GENERATED by scripts/sync-refs.mjs - do not edit.
// Source: skills/forge/SKILL.md routing table (Darkforge plugin).
// Re-run `npm run sync-refs -- --from-local <path>` to refresh.

export interface RoutingRow {
  readonly keywords: readonly string[];
  readonly reference: string;
}

export const ROUTING_TABLE: readonly RoutingRow[] = [
  { keywords: ["animation", "motion", "spring", "transition", "fade", "slide"], reference: "01-framer-motion" },
  { keywords: ["scroll animation", "pin", "scrub", "timeline", "splittext", "parallax"], reference: "02-gsap" },
  { keywords: ["3d", "particles", "webgl", "shader", "fiber", "drei", "sphere", "mesh"], reference: "03-threejs-r3f" },
  { keywords: ["aceternity", "tracing beam", "spotlight", "wavy", "beams", "meteors"], reference: "04-aceternity" },
  { keywords: ["magic ui", "meteor", "shimmer", "grid pattern", "blur fade", "ticker"], reference: "05-magicui" },
  { keywords: ["skiper", "scroll component", "premium animation"], reference: "06-skiper-ui" },
  { keywords: ["reactbits", "animated text", "rotating text"], reference: "07-reactbits" },
  { keywords: ["shadcn", "radix", "dialog", "popover", "command palette"], reference: "08-shadcn-dark" },
  { keywords: ["daisy", "daisyui", "component class"], reference: "09-daisyui-dark" },
  { keywords: ["flowbite"], reference: "10-flowbite-dark" },
  { keywords: ["ant design", "antd", "table", "form antd"], reference: "11-antdesign-dark" },
  { keywords: ["tailwind", "utility class", "container query", "layer"], reference: "12-tailwind-v4" },
  { keywords: ["react spring", "physics", "drag", "gesture", "parallax tilt"], reference: "13-react-spring" },
  { keywords: ["anime", "animejs", "lightweight animation", "svg morph"], reference: "14-animejs" },
  { keywords: ["lottie", "json animation", "after effects"], reference: "15-lottie" },
  { keywords: ["vanta", "spline", "animated background", "embed 3d"], reference: "16-vanta-spline" },
  { keywords: ["skeleton", "loading state", "placeholder", "suspense fallback"], reference: "17-skeleton-system" },
  { keywords: ["hero", "above the fold", "landing top", "masthead"], reference: "patterns/hero" },
  { keywords: ["navbar", "header", "nav", "topbar"], reference: "patterns/navbar" },
  { keywords: ["pricing", "plan", "subscription", "tier"], reference: "patterns/pricing" },
  { keywords: ["dashboard", "stats", "sidebar", "admin", "agent ui"], reference: "patterns/dashboard" },
  { keywords: ["feature", "bento", "grid", "benefit"], reference: "patterns/features" },
  { keywords: ["testimonial", "review", "quote", "social proof"], reference: "patterns/testimonials" },
  { keywords: ["footer", "links", "sitemap"], reference: "patterns/footer" },
  { keywords: ["cta", "call to action", "conversion", "sign up section"], reference: "patterns/cta" },
  { keywords: ["product", "3d showcase", "model"], reference: "patterns/3d-scene" },
  { keywords: ["scroll story", "narrative", "pin section", "scrubbed scene"], reference: "patterns/scroll-story" },
  { keywords: ["like linear", "like stripe", "like vercel", "like raycast", "like framer", "like arc", "like resend", "like anthropic", "awwwards-style", "real-site inspiration"], reference: "inspiration-tour" },
  { keywords: ["light theme", "light mode", "`--light` flag", "white background", "day mode"], reference: "18-light-theme" },
  { keywords: ["once ui", "full design system", "scroll storytelling"], reference: "19-once-ui" },
  { keywords: ["mantine", "mantine ui", "120 components", "mantine hooks"], reference: "20-mantine" },
  { keywords: ["heroui", "hero ui", "dark first"], reference: "21-heroui" },
  { keywords: ["nyxhora", "nyxhora ui", "dashboard library", "saas dashboard"], reference: "22-nyxhora-ui" },
  { keywords: ["animata", "animation snippets", "motion playground", "magnetic button"], reference: "23-animata" },
  { keywords: ["inspira ui", "vue components", "vue animation", "nuxt"], reference: "24-inspira-ui" },
  { keywords: ["float ui", "multi-framework", "svelte components", "html templates"], reference: "25-float-ui" },
  { keywords: ["lenis", "smooth scroll", "inertia scroll"], reference: "26-lenis-smooth-scroll" },
  { keywords: ["locomotive scroll", "parallax scroll", "agency scroll"], reference: "27-locomotive-scroll" },
  { keywords: ["scrollreveal", "simple scroll reveal", "sr.reveal"], reference: "28-scrollreveal" },
  { keywords: ["aos", "animate on scroll", "data-aos"], reference: "29-aos-scroll" },
  { keywords: ["motion library", "popmotion", "lightweight motion", "motion.dev"], reference: "30-motion-universal" },
  { keywords: ["mojs", "mo.js", "burst effects", "celebration", "like button explosion"], reference: "31-mojs-bursts" },
  { keywords: ["moving letters", "text reveals", "typographic animation", "letter stagger"], reference: "32-moving-letters" },
  { keywords: ["ldrs", "loaders", "spinner", "loading dots", "web component loader"], reference: "33-ldrs-loaders" },
];

/**
 * Lowercased keyword phrase -> ordered list of reference names.
 * Multiple rows may share a keyword; values preserve routing-table order.
 */
export const KEYWORD_TO_REFS: ReadonlyMap<string, readonly string[]> = (() => {
  const map = new Map<string, string[]>();
  for (const row of ROUTING_TABLE) {
    for (const keyword of row.keywords) {
      const list = map.get(keyword);
      if (list) list.push(row.reference);
      else map.set(keyword, [row.reference]);
    }
  }
  return map;
})();
