/**
 * Reference router. Wraps the auto-generated routing table with a single
 * keyword-scan function. The generated module is regenerated by
 * scripts/sync-refs.mjs from the plugin's SKILL.md.
 *
 * Matching rules:
 *   - Keywords are lowercased phrases. A row matches the description if any
 *     of its keywords appears as a substring in the lowercased description.
 *   - Word boundaries are not enforced for short keywords either; the routing
 *     table itself was authored with this in mind ("3d", "antd", "aos" rely
 *     on substring matches against natural-language descriptions).
 *   - Returned reference names preserve routing-table order. Duplicates are
 *     dropped (a row can match via multiple keywords without being repeated).
 */

import { ROUTING_TABLE, KEYWORD_TO_REFS, type RoutingRow } from "./reference-router.generated.js";

export { ROUTING_TABLE, KEYWORD_TO_REFS };
export type { RoutingRow };

export function routeIntent(description: string): string[] {
  if (!description) return [];
  const lower = description.toLowerCase();
  const matched: string[] = [];
  const seen = new Set<string>();
  for (const row of ROUTING_TABLE) {
    if (seen.has(row.reference)) continue;
    for (const keyword of row.keywords) {
      if (lower.includes(keyword)) {
        matched.push(row.reference);
        seen.add(row.reference);
        break;
      }
    }
  }
  return matched;
}
