/**
 * Reference router. Wraps the auto-generated routing table from the plugin's
 * SKILL.md with a hand-maintained synonym table and a multi-match scorer.
 *
 * Why two tables:
 *   - `ROUTING_TABLE` (generated) is the literal SKILL.md Phase 2 table —
 *     library names, plugin-author vocabulary. Regenerated by sync-refs, so
 *     edits there get overwritten.
 *   - `MANUAL_SYNONYMS` (this file) is style and intent vocabulary — "glass",
 *     "neon", "stagger", "partner logos", "marquee" — words real users type
 *     that the plugin SKILL.md gets away with not enumerating because the
 *     plugin keeps SKILL.md always-loaded. The MCP server has no equivalent
 *     always-loaded layer, so style/intent words must be explicitly routed.
 *
 * Always-load:
 *   - `00-dark-tokens` is unconditionally returned as the first reference for
 *     every call. It's the design-system foundation (token system, glass
 *     utility classes, neon glow utilities, transitions). Treating it as
 *     conditionally-routed makes generation generic.
 *
 * Matching:
 *   - Case-insensitive substring against the lowercased description.
 *   - Manual synonyms walked before generated routing — style/intent wins
 *     over literal lib names when both could match.
 *   - Refs grouped by category (tokens → lib → pattern), capped at 4.
 *   - Empty description still returns ["00-dark-tokens"].
 */

import { ROUTING_TABLE, KEYWORD_TO_REFS, type RoutingRow } from "./reference-router.generated.js";

export { ROUTING_TABLE, KEYWORD_TO_REFS };
export type { RoutingRow };

/** Always-loaded reference. Returned first, every call. */
const ALWAYS_LOAD = "00-dark-tokens";

/** Maximum references returned by `routeIntent`. */
const MAX_REFS = 4;

/**
 * Hand-maintained style/intent vocabulary. Additions only — never overrides
 * a generated row. Walked before the generated table so style words shape
 * routing for prompts that don't name a literal library.
 */
export const MANUAL_SYNONYMS: readonly RoutingRow[] = [
  // Style cues — these all reinforce always-load tokens, included for documentation
  // and so descriptions like "neon edge glow" fail loudly if the always-load is removed.
  { keywords: ["glass", "glassmorphism", "blur card", "frosted"], reference: ALWAYS_LOAD },
  { keywords: ["neon", "glow", "glowing", "edge glow", "ambient glow"], reference: ALWAYS_LOAD },

  // Motion intent — generated table only knows literal lib names.
  { keywords: ["stagger", "staggered", "sequence", "cascade"], reference: "01-framer-motion" },

  // Pattern intent — words real users type for layouts.
  { keywords: ["hero", "masthead", "above the fold", "landing top"], reference: "patterns/hero" },
  { keywords: ["partner", "logo", "logos", "brand strip", "marquee", "logo strip"], reference: "patterns/features" },
  { keywords: ["card", "chip", "tile", "feature card"], reference: "patterns/features" },
  { keywords: ["bento", "layout grid"], reference: "patterns/features" },
  { keywords: ["pricing", "tier", "plan", "subscription"], reference: "patterns/pricing" },
  { keywords: ["dashboard", "sidebar", "admin"], reference: "patterns/dashboard" },
  { keywords: ["testimonial", "quote", "review", "social proof"], reference: "patterns/testimonials" },
  { keywords: ["footer", "sitemap"], reference: "patterns/footer" },
  { keywords: ["cta", "call to action", "conversion", "sign up"], reference: "patterns/cta" },
  { keywords: ["button", "cta button"], reference: "patterns/cta" },

  // Library intent — pull skeleton/modal/3d refs in on intent words, not just lib names.
  { keywords: ["skeleton", "loading", "placeholder", "suspense"], reference: "17-skeleton-system" },
  { keywords: ["modal", "dialog", "drawer", "sheet"], reference: "08-shadcn-dark" },
  { keywords: ["magnetic", "magnetic button"], reference: "23-animata" },
  { keywords: ["particle", "particles", "shader", "mesh", "webgl scene"], reference: "03-threejs-r3f" },
];

type RefCategory = "tokens" | "lib" | "pattern";

function classifyRef(ref: string): RefCategory {
  if (ref === ALWAYS_LOAD) return "tokens";
  if (ref.startsWith("patterns/")) return "pattern";
  return "lib";
}

/**
 * Returns up to 4 references ordered by category: tokens, then lib matches,
 * then pattern matches. Always includes 00-dark-tokens. Empty description
 * returns just the always-load.
 */
export function routeIntent(description: string): string[] {
  const lower = (description ?? "").toLowerCase().trim();
  const seen = new Set<string>([ALWAYS_LOAD]);
  const libMatches: string[] = [];
  const patternMatches: string[] = [];

  if (lower) {
    // Manual synonyms first — style/intent wins over literal lib names when both could match.
    for (const row of [...MANUAL_SYNONYMS, ...ROUTING_TABLE]) {
      if (seen.has(row.reference)) continue;
      for (const keyword of row.keywords) {
        if (lower.includes(keyword)) {
          seen.add(row.reference);
          if (classifyRef(row.reference) === "pattern") patternMatches.push(row.reference);
          else libMatches.push(row.reference);
          break;
        }
      }
    }
  }

  return [ALWAYS_LOAD, ...libMatches, ...patternMatches].slice(0, MAX_REFS);
}
